name: vriddhi_0
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.1.0
  font_awesome_flutter: ^10.4.0
  http: ^0.13.5
  flutter_form_builder: ^7.8.0
  form_builder_validators: ^8.5.0
  path_provider: ^2.0.14
  file_picker: ^5.2.6
  image_picker: ^0.8.7
  firebase_core: ^2.8.0
  firebase_auth: ^4.3.0
  cloud_firestore: ^4.4.5
  change_case: ^1.0.0+3
  geolocator: ^9.0.2
  provider: ^6.0.5
  google_sign_in: ^5.0.0
  youtube_player_flutter: ^8.1.2
  cached_network_image: ^3.0.0
  url_launcher: ^6.1.11
  flutter_tts: ^3.6.3
  intl: ^0.17.0
  material_dialogs: ^1.1.4
  shared_preferences: ^2.1.1
#  google_ml_kit: ^0.14.0
#  google_cloud_translation: ^0.0.3
  google_maps_flutter: ^2.2.8
  geocoding: ^2.1.0
  google_mlkit_translation: ^0.6.0




dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/logo/
     - assets/images/weather/
     - assets/images/feature_icons/
#     - assets/images/crops
     - assets/images/scenes_farming/
     - assets/images/temp/
     - assets/images/pool_features/
     - assets/images/plant_diseases/
     - assets/images/categories/
     - assets/task.json
     - assets/disease_guide.json
     - assets/farming_technique.json
     - assets/lottie_animations.json
     - assets/homeScreenAnimation.json
     - assets/tractor.json


  fonts:
     - family: Jaldi
       fonts:
         - asset: assets/fonts/Jaldi-Regular.ttf
         - asset: assets/fonts/Jaldi-Bold.ttf


     - family: Catamaran
       fonts:
         - asset: assets/fonts/Catamaran/Catamaran-VariableFont_wght.ttf

     - family: Blinker
       fonts:
         - asset: assets/fonts/Blinker/Blinker-Regular.ttf
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
